export const dummyMusicData = [
  {
    id: 1,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "The Great Album I've ever heard of! ",
    review:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 2,
    category: "music",
    title: "blueblue",
    artist: "Sam Gendel",
    released: "1984-01-01",
    rate: 3.5,
    summary: "Jazzing is good",
    review:
      " variations of passages of variations of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/NF6xy6T5Idm87CdVzAv54OLInF5ulBBYCKvBli4KS6o/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0OTk0/MDUxLTE2NjcxMzA2/NDktOTI3NC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 3,
    category: "music",
    title: "You're Dead!",
    artist: "Flying Lotus",
    released: "1984-01-01",
    rate: 5,
    summary: "I'm Dead!",
    review:
      " injected humour, or injected humour, or injected humour, or injected humour, or  of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. ",
    imageUrl:
      "https://bonuscut.files.wordpress.com/2014/10/flying-lotus-youre-dead_2.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 4,
    category: "music",
    title: "The Anecdote",
    artist: "이센스",
    released: "2015-01-01",
    rate: 4.5,
    summary: "gdogodogdogodogdogodgodogdo",
    review:
      "dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not on",
    imageUrl: "https://image.bugsm.co.kr/album/images/500/5280/528094.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 5,
    category: "music",
    title: "Talk Memory",
    artist: "BAD BAD NOT GOOD",
    released: "2016-07-01",
    rate: 4,
    summary: "Let'ssssssssdascxzccas",
    review:
      " and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a ",
    imageUrl: "https://f4.bcbits.com/img/a0196386795_10.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 6,
    category: "music",
    title: "Zissou",
    artist: "화지",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://cdnimg.melon.co.kr/cm/album/images/026/65/101/2665101_500.jpg?d825fff3c806ab43d386b7d12e433cfb/melon/optimize/90",
    postDate: "2022-01-01",
  },
  {
    id: 7,
    category: "music",
    title: "000 CHANNEL",
    artist: "_BY.ALEXANDER",
    released: "2020-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.scdn.co/image/ab67616d0000b27344802dc485228e30dde733e5",
    postDate: "2022-01-01",
  },
  {
    id: 8,
    category: "music",
    title: "Snaxx",
    artist: "Mndsgn",
    released: "1984-01-01",
    rate: 4.5,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl: "https://f4.bcbits.com/img/a0234931428_10.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 9,
    category: "music",
    title: "Endless",
    artist: "Frank Ocean",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.guim.co.uk/img/media/e63e6367e928c7d83d0c8e8e4a260c8c6c24ee93/0_0_1198_719/master/1198.jpg?width=700&quality=85&auto=format&fit=max&s=96aa465b516c8c73fd7a7e179055a7e7",
    postDate: "2022-01-01",
  },
  {
    id: 10,
    category: "music",
    title: "The Sun's Tirade",
    artist: "Isaiah Rashad",
    released: "1984-01-01",
    rate: 3.5,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://media.pitchfork.com/photos/5929bd38c0084474cd0c2c57/1:1/w_600/621d6053.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 11,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://cdns-images.dzcdn.net/images/cover/0245da6981524b45f615257ff8fbf36b/264x264.jpg",
  },
  {
    id: 12,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 13,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 14,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 15,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 16,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "The Great Album I've ever heard of! ",
    review:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 17,
    category: "music",
    title: "blueblue",
    artist: "Sam Gendel",
    released: "1984-01-01",
    rate: 3.5,
    summary: "Jazzing is good",
    review:
      " variations of passages of variations of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/NF6xy6T5Idm87CdVzAv54OLInF5ulBBYCKvBli4KS6o/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0OTk0/MDUxLTE2NjcxMzA2/NDktOTI3NC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 18,
    category: "music",
    title: "You're Dead!",
    artist: "Flying Lotus",
    released: "1984-01-01",
    rate: 5,
    summary: "I'm Dead!",
    review:
      " injected humour, or injected humour, or injected humour, or injected humour, or  of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. ",
    imageUrl:
      "https://bonuscut.files.wordpress.com/2014/10/flying-lotus-youre-dead_2.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 19,
    category: "music",
    title: "The Anecdote",
    artist: "이센스",
    released: "2015-01-01",
    rate: 4.5,
    summary: "gdogodogdogodogdogodgodogdo",
    review:
      "dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not on",
    imageUrl: "https://image.bugsm.co.kr/album/images/500/5280/528094.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 20,
    category: "music",
    title: "Talk Memory",
    artist: "BAD BAD NOT GOOD",
    released: "2016-07-01",
    rate: 4,
    summary: "Let'ssssssssdascxzccas",
    review:
      " and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a ",
    imageUrl: "https://f4.bcbits.com/img/a0196386795_10.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 21,
    category: "music",
    title: "Zissou",
    artist: "화지",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://cdnimg.melon.co.kr/cm/album/images/026/65/101/2665101_500.jpg?d825fff3c806ab43d386b7d12e433cfb/melon/optimize/90",
    postDate: "2022-01-01",
  },
  {
    id: 22,
    category: "music",
    title: "000 CHANNEL",
    artist: "_BY.ALEXANDER",
    released: "2020-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.scdn.co/image/ab67616d0000b27344802dc485228e30dde733e5",
    postDate: "2022-01-01",
  },
  {
    id: 23,
    category: "music",
    title: "Snaxx",
    artist: "Mndsgn",
    released: "1984-01-01",
    rate: 4.5,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl: "https://f4.bcbits.com/img/a0234931428_10.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 24,
    category: "music",
    title: "Endless",
    artist: "Frank Ocean",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.guim.co.uk/img/media/e63e6367e928c7d83d0c8e8e4a260c8c6c24ee93/0_0_1198_719/master/1198.jpg?width=700&quality=85&auto=format&fit=max&s=96aa465b516c8c73fd7a7e179055a7e7",
    postDate: "2022-01-01",
  },
  {
    id: 25,
    category: "music",
    title: "The Sun's Tirade",
    artist: "Isaiah Rashad",
    released: "1984-01-01",
    rate: 3.5,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://media.pitchfork.com/photos/5929bd38c0084474cd0c2c57/1:1/w_600/621d6053.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 26,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://cdns-images.dzcdn.net/images/cover/0245da6981524b45f615257ff8fbf36b/264x264.jpg",
  },
  {
    id: 27,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 28,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 29,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 30,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 31,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "The Great Album I've ever heard of! ",
    review:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 32,
    category: "music",
    title: "blueblue",
    artist: "Sam Gendel",
    released: "1984-01-01",
    rate: 3.5,
    summary: "Jazzing is good",
    review:
      " variations of passages of variations of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/NF6xy6T5Idm87CdVzAv54OLInF5ulBBYCKvBli4KS6o/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0OTk0/MDUxLTE2NjcxMzA2/NDktOTI3NC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 33,
    category: "music",
    title: "You're Dead!",
    artist: "Flying Lotus",
    released: "1984-01-01",
    rate: 5,
    summary: "I'm Dead!",
    review:
      " injected humour, or injected humour, or injected humour, or injected humour, or  of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. ",
    imageUrl:
      "https://bonuscut.files.wordpress.com/2014/10/flying-lotus-youre-dead_2.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 34,
    category: "music",
    title: "The Anecdote",
    artist: "이센스",
    released: "2015-01-01",
    rate: 4.5,
    summary: "gdogodogdogodogdogodgodogdo",
    review:
      "dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not on",
    imageUrl: "https://image.bugsm.co.kr/album/images/500/5280/528094.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 35,
    category: "music",
    title: "Talk Memory",
    artist: "BAD BAD NOT GOOD",
    released: "2016-07-01",
    rate: 4,
    summary: "Let'ssssssssdascxzccas",
    review:
      " and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a ",
    imageUrl: "https://f4.bcbits.com/img/a0196386795_10.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 36,
    category: "music",
    title: "Zissou",
    artist: "화지",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://cdnimg.melon.co.kr/cm/album/images/026/65/101/2665101_500.jpg?d825fff3c806ab43d386b7d12e433cfb/melon/optimize/90",
    postDate: "2022-01-01",
  },
  {
    id: 37,
    category: "music",
    title: "000 CHANNEL",
    artist: "_BY.ALEXANDER",
    released: "2020-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.scdn.co/image/ab67616d0000b27344802dc485228e30dde733e5",
    postDate: "2022-01-01",
  },
  {
    id: 38,
    category: "music",
    title: "Snaxx",
    artist: "Mndsgn",
    released: "1984-01-01",
    rate: 4.5,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl: "https://f4.bcbits.com/img/a0234931428_10.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 39,
    category: "music",
    title: "Endless",
    artist: "Frank Ocean",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.guim.co.uk/img/media/e63e6367e928c7d83d0c8e8e4a260c8c6c24ee93/0_0_1198_719/master/1198.jpg?width=700&quality=85&auto=format&fit=max&s=96aa465b516c8c73fd7a7e179055a7e7",
    postDate: "2022-01-01",
  },
  {
    id: 40,
    category: "music",
    title: "The Sun's Tirade",
    artist: "Isaiah Rashad",
    released: "1984-01-01",
    rate: 3.5,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://media.pitchfork.com/photos/5929bd38c0084474cd0c2c57/1:1/w_600/621d6053.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 41,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://cdns-images.dzcdn.net/images/cover/0245da6981524b45f615257ff8fbf36b/264x264.jpg",
  },
  {
    id: 42,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 43,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 44,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 45,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "I'm Dead!",
    review: "The Great Album I've ever heard of! ",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 46,
    category: "music",
    title: "Late Late Summer",
    artist: "Bread & Butter",
    released: "1984-01-01",
    rate: 4,
    summary: "The Great Album I've ever heard of! ",
    review:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/ftWfXN5OThRP8E3lSwr03uY9XCZR1WU1TjX5AJzsXpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMzUz/OTY5LTE0OTU4NjU5/MTAtNDU5MC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 47,
    category: "music",
    title: "blueblue",
    artist: "Sam Gendel",
    released: "1984-01-01",
    rate: 3.5,
    summary: "Jazzing is good",
    review:
      " variations of passages of variations of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    imageUrl:
      "https://i.discogs.com/NF6xy6T5Idm87CdVzAv54OLInF5ulBBYCKvBli4KS6o/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0OTk0/MDUxLTE2NjcxMzA2/NDktOTI3NC5qcGVn.jpeg",
    postDate: "2022-01-01",
  },
  {
    id: 48,
    category: "music",
    title: "You're Dead!",
    artist: "Flying Lotus",
    released: "1984-01-01",
    rate: 5,
    summary: "I'm Dead!",
    review:
      " injected humour, or injected humour, or injected humour, or injected humour, or  of passages ofsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (inje like). It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.There are many variations of passages of  variations of passages of variations of passages of variations of passages ofLorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. ",
    imageUrl:
      "https://bonuscut.files.wordpress.com/2014/10/flying-lotus-youre-dead_2.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 49,
    category: "music",
    title: "The Anecdote",
    artist: "이센스",
    released: "2015-01-01",
    rate: 4.5,
    summary: "gdogodogdogodogdogodgodogdo",
    review:
      "dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not on",
    imageUrl: "https://image.bugsm.co.kr/album/images/500/5280/528094.jpg",
    postDate: "2022-01-01",
  },
  {
    id: 50,
    category: "music",
    title: "Talk Memory",
    artist: "BAD BAD NOT GOOD",
    released: "2016-07-01",
    rate: 4,
    summary: "Let'ssssssssdascxzccas",
    review:
      " and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not ondummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a ",
    imageUrl: "https://f4.bcbits.com/img/a0196386795_10.jpg",
    postDate: "2022-01-01",
  },
];
